# Generated by Django 5.0.1 on 2024-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0005_customuser_type_doctorprofile_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
