# Generated by Django 5.0.1 on 2024-02-12 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0005_customuser_type_doctorprofile_patientprofile'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_doctor', to='accountsapp.doctorprofile'),
            preserve_default=False,
        ),
    ]
