# Generated by Django 5.0.1 on 2024-02-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_patientdetectionresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetectionresults',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetectionresults',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
