# Generated by Django 4.2.9 on 2024-03-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_doctordetectionresults_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetectionresults',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='detected_image'),
        ),
    ]
