# Generated by Django 4.2.9 on 2024-04-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_patientdetectionresults_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetectionresults',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='detected_image'),
        ),
    ]
