# Generated by Django 4.2.9 on 2024-05-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_patientdetectionresults_result_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetectionresults',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
