# Generated by Django 4.2.9 on 2024-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_patientdetectionresults_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetectionresults',
            name='points',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
