# Generated by Django 4.2.9 on 2024-05-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_doctordetectionresults_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
