# Generated by Django 4.2.9 on 2024-05-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_patients_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetectionresults',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='detected_image/doctors_patient'),
        ),
        migrations.AlterField(
            model_name='patientdetectionresults',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='detected_image/patients'),
        ),
    ]
