# Generated by Django 4.2.9 on 2024-05-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_doctordetectionresults_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetectionresults',
            name='points',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetectionresults',
            name='points',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
