# Generated by Django 4.2.9 on 2024-07-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_patientdetectionresults_description_arabic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetectionresults',
            name='description_arabic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctordetectionresults',
            name='points_arabic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
